[project]
name = "plantuml-converter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.1",
    "javalang>=0.13.0",
    "tree-sitter>=0.25.2",
    "tree-sitter-kotlin>=1.1.0",
]
